* EQ-lips tools
** Description
Some tools used for the design of [[http://github.com/cbr/EQ-lips-schematic][EQ-lips schematics]].

EQ-lips is a graphic equalizer pedal effect with the following
features:
  - 10 bands of EQ and global gain control with a range of +/-18dB
  - 23 memory banks
  - Analog signal treatment
  - Equalization configuration with LCD and rotary encoder

** Requirements
   - [[http://python.org/][Python]]
   - [[http://numpy.scipy.org/][numpy]]

All these tools can be found in standard packages of most Linux distributions.
They can also be found for other operating systems such as MS Windows.

** Usage
/TBD/. In the meanwhile, use [[http://en.wikipedia.org/wiki/Trial_and_error][Trial and error method]]...

** Author
Cédric Brégardis (cedric.bregardis <at> gmail.com)

** Licence
EQ-lips tools is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the Free
Software Foundation, version 3 of the License.

EQ-lips tools is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
EQ-lips tools.  If not, see [[http://www.gnu.org/licenses/]].
